"""Constants for SMA Akku Steuerung."""

DOMAIN = "akkusteuerung_sma"
VERSION = "0.3.0"
DEFAULT_NAME = "SMA Akku Steuerung"

# Canonical source mapping from opti_mapping.example.yaml
CONF_BATTERY_SOC_ENTITY = "battery_soc_entity"
CONF_BATTERY_TEMP_ENTITY = "battery_temp_entity"
CONF_BATTERY_CAPACITY_ENTITY = "battery_capacity_entity"
CONF_BATTERY_CAPACITY_UNIT = "battery_capacity_unit"
CONF_PV_POWER_ENTITY = "pv_power_entity"
CONF_PV_GENERATION_ENTITY = "pv_generation_entity"
CONF_GRID_EXPORT_ENTITY = "grid_export_entity"
CONF_GRID_IMPORT_ENTITY = "grid_import_entity"
CONF_HOUSE_CONSUMPTION_ENTITY = "house_consumption_entity"
CONF_PRICE_CURRENT_ENTITY = "price_current_entity"
CONF_PRICE_SERIES_ENTITY = "price_series_entity"
CONF_PRICE_UNIT = "price_unit"
CONF_FORECAST_TODAY_ENTITY = "forecast_today_entity"
CONF_FORECAST_TOMORROW_ENTITY = "forecast_tomorrow_entity"
CONF_FORECAST_REMAINING_ENTITY = "forecast_remaining_entity"
CONF_BATTERY_CHARGE_POWER_ENTITY = "battery_charge_power_entity"
CONF_BATTERY_DISCHARGE_POWER_ENTITY = "battery_discharge_power_entity"

CAPACITY_UNIT_WH = "Wh"
CAPACITY_UNIT_KWH = "kWh"
PRICE_UNIT_EUR_KWH = "EUR/kWh"
PRICE_UNIT_CT_KWH = "ct/kWh"
